//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "drugbank-type", Namespace = "http://www.drugbank.ca")]
[System.Xml.Serialization.XmlRootAttribute("drugbank", Namespace = "http://www.drugbank.ca", IsNullable = false)]
public partial class drugbanktype
{

	private drugtype[] drugField;

	private string versionField;

	private System.DateTime exportedonField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drug")]
	public drugtype[] drug
	{
		get
		{
			return this.drugField;
		}
		set
		{
			this.drugField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string version
	{
		get
		{
			return this.versionField;
		}
		set
		{
			this.versionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute("exported-on", DataType = "date")]
	public System.DateTime exportedon
	{
		get
		{
			return this.exportedonField;
		}
		set
		{
			this.exportedonField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "drug-type", Namespace = "http://www.drugbank.ca")]
public partial class drugtype
{

	private drugbankdrugsaltidtype[] drugbankidField;

	private string nameField;

	private string descriptionField;

	private string casnumberField;

	private string uniiField;

	private float averagemassField;

	private bool averagemassFieldSpecified;

	private float monoisotopicmassField;

	private bool monoisotopicmassFieldSpecified;

	private statetype stateField;

	private bool stateFieldSpecified;

	private grouplisttype groupsField;

	private referencelisttype generalreferencesField;

	private string synthesisreferenceField;

	private string indicationField;

	private string pharmacodynamicsField;

	private string mechanismofactionField;

	private string toxicityField;

	private string metabolismField;

	private string absorptionField;

	private string halflifeField;

	private string proteinbindingField;

	private string routeofeliminationField;

	private string volumeofdistributionField;

	private string clearanceField;

	private classificationtype classificationField;

	private salttype[] saltsField;

	private synonymtype[] synonymsField;

	private producttype[] productsField;

	private internationalbrandtype[] internationalbrandsField;

	private mixturetype[] mixturesField;

	private packagertype[] packagersField;

	private manufacturertype[] manufacturersField;

	private pricetype[] pricesField;

	private categorytype[] categoriesField;

	private string[] affectedorganismsField;

	private dosagetype[] dosagesField;

	private atccodetype[] atccodesField;

	private string[] ahfscodesField;

	private string[] pdbentriesField;

	private string fdalabelField;

	private string msdsField;

	private patenttype[] patentsField;

	private string[] foodinteractionsField;

	private druginteractiontype[] druginteractionsField;

	private sequencelisttypeSequence[] sequencesField;

	private calculatedpropertytype[] calculatedpropertiesField;

	private experimentalpropertytype[] experimentalpropertiesField;

	private externalidentifiertype[] externalidentifiersField;

	private externallinktype[] externallinksField;

	private pathwaytype[] pathwaysField;

	private reactiontype[] reactionsField;

	private snpeffecttype[] snpeffectsField;

	private snpadversedrugreactiontype[] snpadversedrugreactionsField;

	private targettype[] targetsField;

	private enzymetype[] enzymesField;

	private carriertype[] carriersField;

	private transportertype[] transportersField;

	private drugtypeType typeField;

	private System.DateTime createdField;

	private System.DateTime updatedField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drugbank-id")]
	public drugbankdrugsaltidtype[] drugbankid
	{
		get
		{
			return this.drugbankidField;
		}
		set
		{
			this.drugbankidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("cas-number")]
	public string casnumber
	{
		get
		{
			return this.casnumberField;
		}
		set
		{
			this.casnumberField = value;
		}
	}

	/// <remarks/>
	public string unii
	{
		get
		{
			return this.uniiField;
		}
		set
		{
			this.uniiField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("average-mass")]
	public float averagemass
	{
		get
		{
			return this.averagemassField;
		}
		set
		{
			this.averagemassField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool averagemassSpecified
	{
		get
		{
			return this.averagemassFieldSpecified;
		}
		set
		{
			this.averagemassFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("monoisotopic-mass")]
	public float monoisotopicmass
	{
		get
		{
			return this.monoisotopicmassField;
		}
		set
		{
			this.monoisotopicmassField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool monoisotopicmassSpecified
	{
		get
		{
			return this.monoisotopicmassFieldSpecified;
		}
		set
		{
			this.monoisotopicmassFieldSpecified = value;
		}
	}

	/// <remarks/>
	public statetype state
	{
		get
		{
			return this.stateField;
		}
		set
		{
			this.stateField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool stateSpecified
	{
		get
		{
			return this.stateFieldSpecified;
		}
		set
		{
			this.stateFieldSpecified = value;
		}
	}

	/// <remarks/>
	public grouplisttype groups
	{
		get
		{
			return this.groupsField;
		}
		set
		{
			this.groupsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("general-references")]
	public referencelisttype generalreferences
	{
		get
		{
			return this.generalreferencesField;
		}
		set
		{
			this.generalreferencesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("synthesis-reference")]
	public string synthesisreference
	{
		get
		{
			return this.synthesisreferenceField;
		}
		set
		{
			this.synthesisreferenceField = value;
		}
	}

	/// <remarks/>
	public string indication
	{
		get
		{
			return this.indicationField;
		}
		set
		{
			this.indicationField = value;
		}
	}

	/// <remarks/>
	public string pharmacodynamics
	{
		get
		{
			return this.pharmacodynamicsField;
		}
		set
		{
			this.pharmacodynamicsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("mechanism-of-action")]
	public string mechanismofaction
	{
		get
		{
			return this.mechanismofactionField;
		}
		set
		{
			this.mechanismofactionField = value;
		}
	}

	/// <remarks/>
	public string toxicity
	{
		get
		{
			return this.toxicityField;
		}
		set
		{
			this.toxicityField = value;
		}
	}

	/// <remarks/>
	public string metabolism
	{
		get
		{
			return this.metabolismField;
		}
		set
		{
			this.metabolismField = value;
		}
	}

	/// <remarks/>
	public string absorption
	{
		get
		{
			return this.absorptionField;
		}
		set
		{
			this.absorptionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("half-life")]
	public string halflife
	{
		get
		{
			return this.halflifeField;
		}
		set
		{
			this.halflifeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("protein-binding")]
	public string proteinbinding
	{
		get
		{
			return this.proteinbindingField;
		}
		set
		{
			this.proteinbindingField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("route-of-elimination")]
	public string routeofelimination
	{
		get
		{
			return this.routeofeliminationField;
		}
		set
		{
			this.routeofeliminationField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("volume-of-distribution")]
	public string volumeofdistribution
	{
		get
		{
			return this.volumeofdistributionField;
		}
		set
		{
			this.volumeofdistributionField = value;
		}
	}

	/// <remarks/>
	public string clearance
	{
		get
		{
			return this.clearanceField;
		}
		set
		{
			this.clearanceField = value;
		}
	}

	/// <remarks/>
	public classificationtype classification
	{
		get
		{
			return this.classificationField;
		}
		set
		{
			this.classificationField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("salt", IsNullable = false)]
	public salttype[] salts
	{
		get
		{
			return this.saltsField;
		}
		set
		{
			this.saltsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("synonym", IsNullable = false)]
	public synonymtype[] synonyms
	{
		get
		{
			return this.synonymsField;
		}
		set
		{
			this.synonymsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("product", IsNullable = false)]
	public producttype[] products
	{
		get
		{
			return this.productsField;
		}
		set
		{
			this.productsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("international-brands")]
	[System.Xml.Serialization.XmlArrayItemAttribute("international-brand", IsNullable = false)]
	public internationalbrandtype[] internationalbrands
	{
		get
		{
			return this.internationalbrandsField;
		}
		set
		{
			this.internationalbrandsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("mixture", IsNullable = false)]
	public mixturetype[] mixtures
	{
		get
		{
			return this.mixturesField;
		}
		set
		{
			this.mixturesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("packager", IsNullable = false)]
	public packagertype[] packagers
	{
		get
		{
			return this.packagersField;
		}
		set
		{
			this.packagersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("manufacturer", IsNullable = false)]
	public manufacturertype[] manufacturers
	{
		get
		{
			return this.manufacturersField;
		}
		set
		{
			this.manufacturersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("price", IsNullable = false)]
	public pricetype[] prices
	{
		get
		{
			return this.pricesField;
		}
		set
		{
			this.pricesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("category", IsNullable = false)]
	public categorytype[] categories
	{
		get
		{
			return this.categoriesField;
		}
		set
		{
			this.categoriesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("affected-organisms")]
	[System.Xml.Serialization.XmlArrayItemAttribute("affected-organism", IsNullable = false)]
	public string[] affectedorganisms
	{
		get
		{
			return this.affectedorganismsField;
		}
		set
		{
			this.affectedorganismsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("dosage", IsNullable = false)]
	public dosagetype[] dosages
	{
		get
		{
			return this.dosagesField;
		}
		set
		{
			this.dosagesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("atc-codes")]
	[System.Xml.Serialization.XmlArrayItemAttribute("atc-code", IsNullable = false)]
	public atccodetype[] atccodes
	{
		get
		{
			return this.atccodesField;
		}
		set
		{
			this.atccodesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("ahfs-codes")]
	[System.Xml.Serialization.XmlArrayItemAttribute("ahfs-code", IsNullable = false)]
	public string[] ahfscodes
	{
		get
		{
			return this.ahfscodesField;
		}
		set
		{
			this.ahfscodesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("pdb-entries")]
	[System.Xml.Serialization.XmlArrayItemAttribute("pdb-entry", IsNullable = false)]
	public string[] pdbentries
	{
		get
		{
			return this.pdbentriesField;
		}
		set
		{
			this.pdbentriesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("fda-label", DataType = "anyURI")]
	public string fdalabel
	{
		get
		{
			return this.fdalabelField;
		}
		set
		{
			this.fdalabelField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
	public string msds
	{
		get
		{
			return this.msdsField;
		}
		set
		{
			this.msdsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("patent", IsNullable = false)]
	public patenttype[] patents
	{
		get
		{
			return this.patentsField;
		}
		set
		{
			this.patentsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("food-interactions")]
	[System.Xml.Serialization.XmlArrayItemAttribute("food-interaction", IsNullable = false)]
	public string[] foodinteractions
	{
		get
		{
			return this.foodinteractionsField;
		}
		set
		{
			this.foodinteractionsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("drug-interactions")]
	[System.Xml.Serialization.XmlArrayItemAttribute("drug-interaction", IsNullable = false)]
	public druginteractiontype[] druginteractions
	{
		get
		{
			return this.druginteractionsField;
		}
		set
		{
			this.druginteractionsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("sequence", IsNullable = false)]
	public sequencelisttypeSequence[] sequences
	{
		get
		{
			return this.sequencesField;
		}
		set
		{
			this.sequencesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("calculated-properties")]
	[System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
	public calculatedpropertytype[] calculatedproperties
	{
		get
		{
			return this.calculatedpropertiesField;
		}
		set
		{
			this.calculatedpropertiesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("experimental-properties")]
	[System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable = false)]
	public experimentalpropertytype[] experimentalproperties
	{
		get
		{
			return this.experimentalpropertiesField;
		}
		set
		{
			this.experimentalpropertiesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("external-identifiers")]
	[System.Xml.Serialization.XmlArrayItemAttribute("external-identifier", IsNullable = false)]
	public externalidentifiertype[] externalidentifiers
	{
		get
		{
			return this.externalidentifiersField;
		}
		set
		{
			this.externalidentifiersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("external-links")]
	[System.Xml.Serialization.XmlArrayItemAttribute("external-link", IsNullable = false)]
	public externallinktype[] externallinks
	{
		get
		{
			return this.externallinksField;
		}
		set
		{
			this.externallinksField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("pathway", IsNullable = false)]
	public pathwaytype[] pathways
	{
		get
		{
			return this.pathwaysField;
		}
		set
		{
			this.pathwaysField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("reaction", IsNullable = false)]
	public reactiontype[] reactions
	{
		get
		{
			return this.reactionsField;
		}
		set
		{
			this.reactionsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("snp-effects")]
	[System.Xml.Serialization.XmlArrayItemAttribute("effect", IsNullable = false)]
	public snpeffecttype[] snpeffects
	{
		get
		{
			return this.snpeffectsField;
		}
		set
		{
			this.snpeffectsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("snp-adverse-drug-reactions")]
	[System.Xml.Serialization.XmlArrayItemAttribute("reaction", IsNullable = false)]
	public snpadversedrugreactiontype[] snpadversedrugreactions
	{
		get
		{
			return this.snpadversedrugreactionsField;
		}
		set
		{
			this.snpadversedrugreactionsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("target", IsNullable = false)]
	public targettype[] targets
	{
		get
		{
			return this.targetsField;
		}
		set
		{
			this.targetsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("enzyme", IsNullable = false)]
	public enzymetype[] enzymes
	{
		get
		{
			return this.enzymesField;
		}
		set
		{
			this.enzymesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("carrier", IsNullable = false)]
	public carriertype[] carriers
	{
		get
		{
			return this.carriersField;
		}
		set
		{
			this.carriersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("transporter", IsNullable = false)]
	public transportertype[] transporters
	{
		get
		{
			return this.transportersField;
		}
		set
		{
			this.transportersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public drugtypeType type
	{
		get
		{
			return this.typeField;
		}
		set
		{
			this.typeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
	public System.DateTime created
	{
		get
		{
			return this.createdField;
		}
		set
		{
			this.createdField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
	public System.DateTime updated
	{
		get
		{
			return this.updatedField;
		}
		set
		{
			this.updatedField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "drugbank-drug-salt-id-type", Namespace = "http://www.drugbank.ca")]
public partial class drugbankdrugsaltidtype
{

	private bool primaryField;

	private string valueField;

	public drugbankdrugsaltidtype()
	{
		this.primaryField = false;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	[System.ComponentModel.DefaultValueAttribute(false)]
	public bool primary
	{
		get
		{
			return this.primaryField;
		}
		set
		{
			this.primaryField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "transporter-type", Namespace = "http://www.drugbank.ca")]
public partial class transportertype
{

	private string idField;

	private string nameField;

	private string organismField;

	private string[] actionsField;

	private referencelisttype referencesField;

	private knownactiontype knownactionField;

	private polypeptidetype[] polypeptideField;

	private string positionField;

	/// <remarks/>
	public string id
	{
		get
		{
			return this.idField;
		}
		set
		{
			this.idField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string organism
	{
		get
		{
			return this.organismField;
		}
		set
		{
			this.organismField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable = false)]
	public string[] actions
	{
		get
		{
			return this.actionsField;
		}
		set
		{
			this.actionsField = value;
		}
	}

	/// <remarks/>
	public referencelisttype references
	{
		get
		{
			return this.referencesField;
		}
		set
		{
			this.referencesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("known-action")]
	public knownactiontype knownaction
	{
		get
		{
			return this.knownactionField;
		}
		set
		{
			this.knownactionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("polypeptide")]
	public polypeptidetype[] polypeptide
	{
		get
		{
			return this.polypeptideField;
		}
		set
		{
			this.polypeptideField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
	public string position
	{
		get
		{
			return this.positionField;
		}
		set
		{
			this.positionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "reference-list-type", Namespace = "http://www.drugbank.ca")]
public partial class referencelisttype
{

	private articletype[] articlesField;

	private textbooktype[] textbooksField;

	private linktype[] linksField;

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("article", IsNullable = false)]
	public articletype[] articles
	{
		get
		{
			return this.articlesField;
		}
		set
		{
			this.articlesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("textbook", IsNullable = false)]
	public textbooktype[] textbooks
	{
		get
		{
			return this.textbooksField;
		}
		set
		{
			this.textbooksField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable = false)]
	public linktype[] links
	{
		get
		{
			return this.linksField;
		}
		set
		{
			this.linksField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "article-type", Namespace = "http://www.drugbank.ca")]
public partial class articletype
{

	private string pubmedidField;

	private string citationField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("pubmed-id")]
	public string pubmedid
	{
		get
		{
			return this.pubmedidField;
		}
		set
		{
			this.pubmedidField = value;
		}
	}

	/// <remarks/>
	public string citation
	{
		get
		{
			return this.citationField;
		}
		set
		{
			this.citationField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "textbook-type", Namespace = "http://www.drugbank.ca")]
public partial class textbooktype
{

	private string isbnField;

	private string citationField;

	/// <remarks/>
	public string isbn
	{
		get
		{
			return this.isbnField;
		}
		set
		{
			this.isbnField = value;
		}
	}

	/// <remarks/>
	public string citation
	{
		get
		{
			return this.citationField;
		}
		set
		{
			this.citationField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "link-type", Namespace = "http://www.drugbank.ca")]
public partial class linktype
{

	private string titleField;

	private string urlField;

	/// <remarks/>
	public string title
	{
		get
		{
			return this.titleField;
		}
		set
		{
			this.titleField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
	public string url
	{
		get
		{
			return this.urlField;
		}
		set
		{
			this.urlField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "known-action-type", Namespace = "http://www.drugbank.ca")]
public enum knownactiontype
{

	/// <remarks/>
	yes,

	/// <remarks/>
	no,

	/// <remarks/>
	unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "polypeptide-type", Namespace = "http://www.drugbank.ca")]
public partial class polypeptidetype
{

	private string nameField;

	private string generalfunctionField;

	private string specificfunctionField;

	private string genenameField;

	private string locusField;

	private string cellularlocationField;

	private string transmembraneregionsField;

	private string signalregionsField;

	private string theoreticalpiField;

	private string molecularweightField;

	private string chromosomelocationField;

	private polypeptidetypeOrganism organismField;

	private polypeptideexternalidentifiertype[] externalidentifiersField;

	private string[] synonymsField;

	private sequencetype aminoacidsequenceField;

	private sequencetype genesequenceField;

	private pfamtype[] pfamsField;

	private goclassifiertype[] goclassifiersField;

	private string idField;

	private string sourceField;

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("general-function")]
	public string generalfunction
	{
		get
		{
			return this.generalfunctionField;
		}
		set
		{
			this.generalfunctionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("specific-function")]
	public string specificfunction
	{
		get
		{
			return this.specificfunctionField;
		}
		set
		{
			this.specificfunctionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("gene-name")]
	public string genename
	{
		get
		{
			return this.genenameField;
		}
		set
		{
			this.genenameField = value;
		}
	}

	/// <remarks/>
	public string locus
	{
		get
		{
			return this.locusField;
		}
		set
		{
			this.locusField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("cellular-location")]
	public string cellularlocation
	{
		get
		{
			return this.cellularlocationField;
		}
		set
		{
			this.cellularlocationField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("transmembrane-regions")]
	public string transmembraneregions
	{
		get
		{
			return this.transmembraneregionsField;
		}
		set
		{
			this.transmembraneregionsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("signal-regions")]
	public string signalregions
	{
		get
		{
			return this.signalregionsField;
		}
		set
		{
			this.signalregionsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("theoretical-pi")]
	public string theoreticalpi
	{
		get
		{
			return this.theoreticalpiField;
		}
		set
		{
			this.theoreticalpiField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("molecular-weight")]
	public string molecularweight
	{
		get
		{
			return this.molecularweightField;
		}
		set
		{
			this.molecularweightField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("chromosome-location")]
	public string chromosomelocation
	{
		get
		{
			return this.chromosomelocationField;
		}
		set
		{
			this.chromosomelocationField = value;
		}
	}

	/// <remarks/>
	public polypeptidetypeOrganism organism
	{
		get
		{
			return this.organismField;
		}
		set
		{
			this.organismField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("external-identifiers")]
	[System.Xml.Serialization.XmlArrayItemAttribute("external-identifier", IsNullable = false)]
	public polypeptideexternalidentifiertype[] externalidentifiers
	{
		get
		{
			return this.externalidentifiersField;
		}
		set
		{
			this.externalidentifiersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("synonym", IsNullable = false)]
	public string[] synonyms
	{
		get
		{
			return this.synonymsField;
		}
		set
		{
			this.synonymsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("amino-acid-sequence")]
	public sequencetype aminoacidsequence
	{
		get
		{
			return this.aminoacidsequenceField;
		}
		set
		{
			this.aminoacidsequenceField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("gene-sequence")]
	public sequencetype genesequence
	{
		get
		{
			return this.genesequenceField;
		}
		set
		{
			this.genesequenceField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("pfam", IsNullable = false)]
	public pfamtype[] pfams
	{
		get
		{
			return this.pfamsField;
		}
		set
		{
			this.pfamsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayAttribute("go-classifiers")]
	[System.Xml.Serialization.XmlArrayItemAttribute("go-classifier", IsNullable = false)]
	public goclassifiertype[] goclassifiers
	{
		get
		{
			return this.goclassifiersField;
		}
		set
		{
			this.goclassifiersField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string id
	{
		get
		{
			return this.idField;
		}
		set
		{
			this.idField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string source
	{
		get
		{
			return this.sourceField;
		}
		set
		{
			this.sourceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.drugbank.ca")]
public partial class polypeptidetypeOrganism
{

	private string ncbitaxonomyidField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute("ncbi-taxonomy-id")]
	public string ncbitaxonomyid
	{
		get
		{
			return this.ncbitaxonomyidField;
		}
		set
		{
			this.ncbitaxonomyidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "polypeptide-external-identifier-type", Namespace = "http://www.drugbank.ca")]
public partial class polypeptideexternalidentifiertype
{

	private polypeptideexternalidentifierresourcetype resourceField;

	private string identifierField;

	/// <remarks/>
	public polypeptideexternalidentifierresourcetype resource
	{
		get
		{
			return this.resourceField;
		}
		set
		{
			this.resourceField = value;
		}
	}

	/// <remarks/>
	public string identifier
	{
		get
		{
			return this.identifierField;
		}
		set
		{
			this.identifierField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "polypeptide-external-identifier-resource-type", Namespace = "http://www.drugbank.ca")]
public enum polypeptideexternalidentifierresourcetype
{

	/// <remarks/>
	UniProtKB,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("UniProt Accession")]
	UniProtAccession,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("HUGO Gene Nomenclature Committee (HGNC)")]
	HUGOGeneNomenclatureCommitteeHGNC,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Human Protein Reference Database (HPRD)")]
	HumanProteinReferenceDatabaseHPRD,

	/// <remarks/>
	GenAtlas,

	/// <remarks/>
	GeneCards,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("GenBank Gene Database")]
	GenBankGeneDatabase,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("GenBank Protein Database")]
	GenBankProteinDatabase,

	/// <remarks/>
	ChEMBL,

	/// <remarks/>
	IUPHAR,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Guide to Pharmacology")]
	GuidetoPharmacology,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "sequence-type", Namespace = "http://www.drugbank.ca")]
public partial class sequencetype
{

	private string formatField;

	private string valueField;

	public sequencetype()
	{
		this.formatField = "FASTA";
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string format
	{
		get
		{
			return this.formatField;
		}
		set
		{
			this.formatField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "pfam-type", Namespace = "http://www.drugbank.ca")]
public partial class pfamtype
{

	private string identifierField;

	private string nameField;

	/// <remarks/>
	public string identifier
	{
		get
		{
			return this.identifierField;
		}
		set
		{
			this.identifierField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "go-classifier-type", Namespace = "http://www.drugbank.ca")]
public partial class goclassifiertype
{

	private string categoryField;

	private string descriptionField;

	/// <remarks/>
	public string category
	{
		get
		{
			return this.categoryField;
		}
		set
		{
			this.categoryField = value;
		}
	}

	/// <remarks/>
	public string description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "carrier-type", Namespace = "http://www.drugbank.ca")]
public partial class carriertype
{

	private string idField;

	private string nameField;

	private string organismField;

	private string[] actionsField;

	private referencelisttype referencesField;

	private knownactiontype knownactionField;

	private polypeptidetype[] polypeptideField;

	private string positionField;

	/// <remarks/>
	public string id
	{
		get
		{
			return this.idField;
		}
		set
		{
			this.idField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string organism
	{
		get
		{
			return this.organismField;
		}
		set
		{
			this.organismField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable = false)]
	public string[] actions
	{
		get
		{
			return this.actionsField;
		}
		set
		{
			this.actionsField = value;
		}
	}

	/// <remarks/>
	public referencelisttype references
	{
		get
		{
			return this.referencesField;
		}
		set
		{
			this.referencesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("known-action")]
	public knownactiontype knownaction
	{
		get
		{
			return this.knownactionField;
		}
		set
		{
			this.knownactionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("polypeptide")]
	public polypeptidetype[] polypeptide
	{
		get
		{
			return this.polypeptideField;
		}
		set
		{
			this.polypeptideField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
	public string position
	{
		get
		{
			return this.positionField;
		}
		set
		{
			this.positionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "enzyme-type", Namespace = "http://www.drugbank.ca")]
public partial class enzymetype
{

	private string idField;

	private string nameField;

	private string organismField;

	private string[] actionsField;

	private referencelisttype referencesField;

	private knownactiontype knownactionField;

	private polypeptidetype[] polypeptideField;

	private string inhibitionstrengthField;

	private string inductionstrengthField;

	private string positionField;

	/// <remarks/>
	public string id
	{
		get
		{
			return this.idField;
		}
		set
		{
			this.idField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string organism
	{
		get
		{
			return this.organismField;
		}
		set
		{
			this.organismField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable = false)]
	public string[] actions
	{
		get
		{
			return this.actionsField;
		}
		set
		{
			this.actionsField = value;
		}
	}

	/// <remarks/>
	public referencelisttype references
	{
		get
		{
			return this.referencesField;
		}
		set
		{
			this.referencesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("known-action")]
	public knownactiontype knownaction
	{
		get
		{
			return this.knownactionField;
		}
		set
		{
			this.knownactionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("polypeptide")]
	public polypeptidetype[] polypeptide
	{
		get
		{
			return this.polypeptideField;
		}
		set
		{
			this.polypeptideField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("inhibition-strength")]
	public string inhibitionstrength
	{
		get
		{
			return this.inhibitionstrengthField;
		}
		set
		{
			this.inhibitionstrengthField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("induction-strength")]
	public string inductionstrength
	{
		get
		{
			return this.inductionstrengthField;
		}
		set
		{
			this.inductionstrengthField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
	public string position
	{
		get
		{
			return this.positionField;
		}
		set
		{
			this.positionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "target-type", Namespace = "http://www.drugbank.ca")]
public partial class targettype
{

	private string idField;

	private string nameField;

	private string organismField;

	private string[] actionsField;

	private referencelisttype referencesField;

	private knownactiontype knownactionField;

	private polypeptidetype[] polypeptideField;

	private string positionField;

	/// <remarks/>
	public string id
	{
		get
		{
			return this.idField;
		}
		set
		{
			this.idField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string organism
	{
		get
		{
			return this.organismField;
		}
		set
		{
			this.organismField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("action", IsNullable = false)]
	public string[] actions
	{
		get
		{
			return this.actionsField;
		}
		set
		{
			this.actionsField = value;
		}
	}

	/// <remarks/>
	public referencelisttype references
	{
		get
		{
			return this.referencesField;
		}
		set
		{
			this.referencesField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("known-action")]
	public knownactiontype knownaction
	{
		get
		{
			return this.knownactionField;
		}
		set
		{
			this.knownactionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("polypeptide")]
	public polypeptidetype[] polypeptide
	{
		get
		{
			return this.polypeptideField;
		}
		set
		{
			this.polypeptideField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
	public string position
	{
		get
		{
			return this.positionField;
		}
		set
		{
			this.positionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "snp-adverse-drug-reaction-type", Namespace = "http://www.drugbank.ca")]
public partial class snpadversedrugreactiontype
{

	private string[] proteinnameField;

	private string[] genesymbolField;

	private string[] uniprotidField;

	private string[] rsidField;

	private string[] alleleField;

	private string[] adversereactionField;

	private string[] descriptionField;

	private string[] pubmedidField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("protein-name")]
	public string[] proteinname
	{
		get
		{
			return this.proteinnameField;
		}
		set
		{
			this.proteinnameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("gene-symbol")]
	public string[] genesymbol
	{
		get
		{
			return this.genesymbolField;
		}
		set
		{
			this.genesymbolField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("uniprot-id")]
	public string[] uniprotid
	{
		get
		{
			return this.uniprotidField;
		}
		set
		{
			this.uniprotidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("rs-id")]
	public string[] rsid
	{
		get
		{
			return this.rsidField;
		}
		set
		{
			this.rsidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("allele")]
	public string[] allele
	{
		get
		{
			return this.alleleField;
		}
		set
		{
			this.alleleField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("adverse-reaction")]
	public string[] adversereaction
	{
		get
		{
			return this.adversereactionField;
		}
		set
		{
			this.adversereactionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("description")]
	public string[] description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("pubmed-id")]
	public string[] pubmedid
	{
		get
		{
			return this.pubmedidField;
		}
		set
		{
			this.pubmedidField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "snp-effect-type", Namespace = "http://www.drugbank.ca")]
public partial class snpeffecttype
{

	private string[] proteinnameField;

	private string[] genesymbolField;

	private string[] uniprotidField;

	private string[] rsidField;

	private string[] alleleField;

	private string[] definingchangeField;

	private string[] descriptionField;

	private string[] pubmedidField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("protein-name")]
	public string[] proteinname
	{
		get
		{
			return this.proteinnameField;
		}
		set
		{
			this.proteinnameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("gene-symbol")]
	public string[] genesymbol
	{
		get
		{
			return this.genesymbolField;
		}
		set
		{
			this.genesymbolField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("uniprot-id")]
	public string[] uniprotid
	{
		get
		{
			return this.uniprotidField;
		}
		set
		{
			this.uniprotidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("rs-id")]
	public string[] rsid
	{
		get
		{
			return this.rsidField;
		}
		set
		{
			this.rsidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("allele")]
	public string[] allele
	{
		get
		{
			return this.alleleField;
		}
		set
		{
			this.alleleField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("defining-change")]
	public string[] definingchange
	{
		get
		{
			return this.definingchangeField;
		}
		set
		{
			this.definingchangeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("description")]
	public string[] description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("pubmed-id")]
	public string[] pubmedid
	{
		get
		{
			return this.pubmedidField;
		}
		set
		{
			this.pubmedidField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "reaction-enzyme-type", Namespace = "http://www.drugbank.ca")]
public partial class reactionenzymetype
{

	private string drugbankidField;

	private string nameField;

	private string uniprotidField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drugbank-id")]
	public string drugbankid
	{
		get
		{
			return this.drugbankidField;
		}
		set
		{
			this.drugbankidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("uniprot-id")]
	public string uniprotid
	{
		get
		{
			return this.uniprotidField;
		}
		set
		{
			this.uniprotidField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "reaction-element-type", Namespace = "http://www.drugbank.ca")]
public partial class reactionelementtype
{

	private string drugbankidField;

	private string nameField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drugbank-id")]
	public string drugbankid
	{
		get
		{
			return this.drugbankidField;
		}
		set
		{
			this.drugbankidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "reaction-type", Namespace = "http://www.drugbank.ca")]
public partial class reactiontype
{

	private string sequenceField;

	private reactionelementtype leftelementField;

	private reactionelementtype rightelementField;

	private reactionenzymetype[] enzymesField;

	/// <remarks/>
	public string sequence
	{
		get
		{
			return this.sequenceField;
		}
		set
		{
			this.sequenceField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("left-element")]
	public reactionelementtype leftelement
	{
		get
		{
			return this.leftelementField;
		}
		set
		{
			this.leftelementField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("right-element")]
	public reactionelementtype rightelement
	{
		get
		{
			return this.rightelementField;
		}
		set
		{
			this.rightelementField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("enzyme", IsNullable = false)]
	public reactionenzymetype[] enzymes
	{
		get
		{
			return this.enzymesField;
		}
		set
		{
			this.enzymesField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "pathway-drug-type", Namespace = "http://www.drugbank.ca")]
public partial class pathwaydrugtype
{

	private drugbankdrugsaltidtype drugbankidField;

	private string nameField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drugbank-id")]
	public drugbankdrugsaltidtype drugbankid
	{
		get
		{
			return this.drugbankidField;
		}
		set
		{
			this.drugbankidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "pathway-type", Namespace = "http://www.drugbank.ca")]
public partial class pathwaytype
{

	private string smpdbidField;

	private string nameField;

	private string categoryField;

	private pathwaydrugtype[] drugsField;

	private string[] enzymesField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("smpdb-id")]
	public string smpdbid
	{
		get
		{
			return this.smpdbidField;
		}
		set
		{
			this.smpdbidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string category
	{
		get
		{
			return this.categoryField;
		}
		set
		{
			this.categoryField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("drug", IsNullable = false)]
	public pathwaydrugtype[] drugs
	{
		get
		{
			return this.drugsField;
		}
		set
		{
			this.drugsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlArrayItemAttribute("uniprot-id", IsNullable = false)]
	public string[] enzymes
	{
		get
		{
			return this.enzymesField;
		}
		set
		{
			this.enzymesField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "external-link-type", Namespace = "http://www.drugbank.ca")]
public partial class externallinktype
{

	private externallinkresourcetype resourceField;

	private string urlField;

	/// <remarks/>
	public externallinkresourcetype resource
	{
		get
		{
			return this.resourceField;
		}
		set
		{
			this.resourceField = value;
		}
	}

	/// <remarks/>
	public string url
	{
		get
		{
			return this.urlField;
		}
		set
		{
			this.urlField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "external-link-resource-type", Namespace = "http://www.drugbank.ca")]
public enum externallinkresourcetype
{

	/// <remarks/>
	RxList,

	/// <remarks/>
	PDRhealth,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Drugs.com")]
	Drugscom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "external-identifier-type", Namespace = "http://www.drugbank.ca")]
public partial class externalidentifiertype
{

	private externalidentifierresourcetype resourceField;

	private string identifierField;

	/// <remarks/>
	public externalidentifierresourcetype resource
	{
		get
		{
			return this.resourceField;
		}
		set
		{
			this.resourceField = value;
		}
	}

	/// <remarks/>
	public string identifier
	{
		get
		{
			return this.identifierField;
		}
		set
		{
			this.identifierField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "external-identifier-resource-type", Namespace = "http://www.drugbank.ca")]
public enum externalidentifierresourcetype
{

	/// <remarks/>
	UniProtKB,

	/// <remarks/>
	Wikipedia,

	/// <remarks/>
	ChEBI,

	/// <remarks/>
	ChEMBL,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("PubChem Compound")]
	PubChemCompound,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("PubChem Substance")]
	PubChemSubstance,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Drugs Product Database (DPD)")]
	DrugsProductDatabaseDPD,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("KEGG Compound")]
	KEGGCompound,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("KEGG Drug")]
	KEGGDrug,

	/// <remarks/>
	ChemSpider,

	/// <remarks/>
	BindingDB,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("National Drug Code Directory")]
	NationalDrugCodeDirectory,

	/// <remarks/>
	GenBank,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Therapeutic Targets Database")]
	TherapeuticTargetsDatabase,

	/// <remarks/>
	PharmGKB,

	/// <remarks/>
	PDB,

	/// <remarks/>
	IUPHAR,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Guide to Pharmacology")]
	GuidetoPharmacology,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "experimental-property-type", Namespace = "http://www.drugbank.ca")]
public partial class experimentalpropertytype
{

	private experimentalpropertykindtype kindField;

	private string valueField;

	private string sourceField;

	/// <remarks/>
	public experimentalpropertykindtype kind
	{
		get
		{
			return this.kindField;
		}
		set
		{
			this.kindField = value;
		}
	}

	/// <remarks/>
	public string value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}

	/// <remarks/>
	public string source
	{
		get
		{
			return this.sourceField;
		}
		set
		{
			this.sourceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "experimental-property-kind-type", Namespace = "http://www.drugbank.ca")]
public enum experimentalpropertykindtype
{

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Water Solubility")]
	WaterSolubility,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Melting Point")]
	MeltingPoint,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Boiling Point")]
	BoilingPoint,

	/// <remarks/>
	logP,

	/// <remarks/>
	logS,

	/// <remarks/>
	Hydrophobicity,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Isoelectric Point")]
	IsoelectricPoint,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("caco2 Permeability")]
	caco2Permeability,

	/// <remarks/>
	pKa,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Molecular Weight")]
	MolecularWeight,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Molecular Formula")]
	MolecularFormula,

	/// <remarks/>
	Radioactivity,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "calculated-property-type", Namespace = "http://www.drugbank.ca")]
public partial class calculatedpropertytype
{

	private calculatedpropertykindtype kindField;

	private string valueField;

	private calculatedpropertysourcetype sourceField;

	/// <remarks/>
	public calculatedpropertykindtype kind
	{
		get
		{
			return this.kindField;
		}
		set
		{
			this.kindField = value;
		}
	}

	/// <remarks/>
	public string value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}

	/// <remarks/>
	public calculatedpropertysourcetype source
	{
		get
		{
			return this.sourceField;
		}
		set
		{
			this.sourceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "calculated-property-kind-type", Namespace = "http://www.drugbank.ca")]
public enum calculatedpropertykindtype
{

	/// <remarks/>
	logP,

	/// <remarks/>
	logS,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Water Solubility")]
	WaterSolubility,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("IUPAC Name")]
	IUPACName,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Traditional IUPAC Name")]
	TraditionalIUPACName,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Molecular Weight")]
	MolecularWeight,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Monoisotopic Weight")]
	MonoisotopicWeight,

	/// <remarks/>
	SMILES,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Molecular Formula")]
	MolecularFormula,

	/// <remarks/>
	InChI,

	/// <remarks/>
	InChIKey,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Polar Surface Area (PSA)")]
	PolarSurfaceAreaPSA,

	/// <remarks/>
	Refractivity,

	/// <remarks/>
	Polarizability,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Rotatable Bond Count")]
	RotatableBondCount,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("H Bond Acceptor Count")]
	HBondAcceptorCount,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("H Bond Donor Count")]
	HBondDonorCount,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("pKa (strongest acidic)")]
	pKastrongestacidic,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("pKa (strongest basic)")]
	pKastrongestbasic,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Physiological Charge")]
	PhysiologicalCharge,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Number of Rings")]
	NumberofRings,

	/// <remarks/>
	Bioavailability,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Rule of Five")]
	RuleofFive,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Ghose Filter")]
	GhoseFilter,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("MDDR-Like Rule")]
	MDDRLikeRule,

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("Veber\'s Rule")]
	VebersRule,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "calculated-property-source-type", Namespace = "http://www.drugbank.ca")]
public enum calculatedpropertysourcetype
{

	/// <remarks/>
	ChemAxon,

	/// <remarks/>
	ALOGPS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "drug-interaction-type", Namespace = "http://www.drugbank.ca")]
public partial class druginteractiontype
{

	private drugbankdrugsaltidtype drugbankidField;

	private string nameField;

	private string descriptionField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drugbank-id")]
	public drugbankdrugsaltidtype drugbankid
	{
		get
		{
			return this.drugbankidField;
		}
		set
		{
			this.drugbankidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "patent-type", Namespace = "http://www.drugbank.ca")]
public partial class patenttype
{

	private string numberField;

	private string countryField;

	private string approvedField;

	private string expiresField;

	private bool pediatricextensionField;

	/// <remarks/>
	public string number
	{
		get
		{
			return this.numberField;
		}
		set
		{
			this.numberField = value;
		}
	}

	/// <remarks/>
	public string country
	{
		get
		{
			return this.countryField;
		}
		set
		{
			this.countryField = value;
		}
	}

	/// <remarks/>
	public string approved
	{
		get
		{
			return this.approvedField;
		}
		set
		{
			this.approvedField = value;
		}
	}

	/// <remarks/>
	public string expires
	{
		get
		{
			return this.expiresField;
		}
		set
		{
			this.expiresField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("pediatric-extension")]
	public bool pediatricextension
	{
		get
		{
			return this.pediatricextensionField;
		}
		set
		{
			this.pediatricextensionField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "atc-code-level-type", Namespace = "http://www.drugbank.ca")]
public partial class atccodeleveltype
{

	private string codeField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string code
	{
		get
		{
			return this.codeField;
		}
		set
		{
			this.codeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "atc-code-type", Namespace = "http://www.drugbank.ca")]
public partial class atccodetype
{

	private atccodeleveltype[] levelField;

	private string codeField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("level")]
	public atccodeleveltype[] level
	{
		get
		{
			return this.levelField;
		}
		set
		{
			this.levelField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string code
	{
		get
		{
			return this.codeField;
		}
		set
		{
			this.codeField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "dosage-type", Namespace = "http://www.drugbank.ca")]
public partial class dosagetype
{

	private string formField;

	private string routeField;

	private string strengthField;

	/// <remarks/>
	public string form
	{
		get
		{
			return this.formField;
		}
		set
		{
			this.formField = value;
		}
	}

	/// <remarks/>
	public string route
	{
		get
		{
			return this.routeField;
		}
		set
		{
			this.routeField = value;
		}
	}

	/// <remarks/>
	public string strength
	{
		get
		{
			return this.strengthField;
		}
		set
		{
			this.strengthField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "category-type", Namespace = "http://www.drugbank.ca")]
public partial class categorytype
{

	private string categoryField;

	private string meshidField;

	/// <remarks/>
	public string category
	{
		get
		{
			return this.categoryField;
		}
		set
		{
			this.categoryField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("mesh-id")]
	public string meshid
	{
		get
		{
			return this.meshidField;
		}
		set
		{
			this.meshidField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "price-type", Namespace = "http://www.drugbank.ca")]
public partial class pricetype
{

	private string descriptionField;

	private pricetypeCost costField;

	private string unitField;

	/// <remarks/>
	public string description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}

	/// <remarks/>
	public pricetypeCost cost
	{
		get
		{
			return this.costField;
		}
		set
		{
			this.costField = value;
		}
	}

	/// <remarks/>
	public string unit
	{
		get
		{
			return this.unitField;
		}
		set
		{
			this.unitField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.drugbank.ca")]
public partial class pricetypeCost
{

	private string currencyField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string currency
	{
		get
		{
			return this.currencyField;
		}
		set
		{
			this.currencyField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "manufacturer-type", Namespace = "http://www.drugbank.ca")]
public partial class manufacturertype
{

	private bool genericField;

	private bool genericFieldSpecified;

	private string urlField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public bool generic
	{
		get
		{
			return this.genericField;
		}
		set
		{
			this.genericField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool genericSpecified
	{
		get
		{
			return this.genericFieldSpecified;
		}
		set
		{
			this.genericFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
	public string url
	{
		get
		{
			return this.urlField;
		}
		set
		{
			this.urlField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "packager-type", Namespace = "http://www.drugbank.ca")]
public partial class packagertype
{

	private string nameField;

	private string urlField;

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string url
	{
		get
		{
			return this.urlField;
		}
		set
		{
			this.urlField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "mixture-type", Namespace = "http://www.drugbank.ca")]
public partial class mixturetype
{

	private string nameField;

	private string ingredientsField;

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string ingredients
	{
		get
		{
			return this.ingredientsField;
		}
		set
		{
			this.ingredientsField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "international-brand-type", Namespace = "http://www.drugbank.ca")]
public partial class internationalbrandtype
{

	private string nameField;

	private string companyField;

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string company
	{
		get
		{
			return this.companyField;
		}
		set
		{
			this.companyField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "product-type", Namespace = "http://www.drugbank.ca")]
public partial class producttype
{

	private string nameField;

	private string labellerField;

	private string ndcidField;

	private string ndcproductcodeField;

	private string dpdidField;

	private string emaproductcodeField;

	private string emamanumberField;

	private string startedmarketingonField;

	private string endedmarketingonField;

	private string dosageformField;

	private string strengthField;

	private string routeField;

	private string fdaapplicationnumberField;

	private bool genericField;

	private bool overthecounterField;

	private bool approvedField;

	private productcountrytype countryField;

	private productsourcetype sourceField;

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string labeller
	{
		get
		{
			return this.labellerField;
		}
		set
		{
			this.labellerField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ndc-id")]
	public string ndcid
	{
		get
		{
			return this.ndcidField;
		}
		set
		{
			this.ndcidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ndc-product-code")]
	public string ndcproductcode
	{
		get
		{
			return this.ndcproductcodeField;
		}
		set
		{
			this.ndcproductcodeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("dpd-id", IsNullable = true)]
	public string dpdid
	{
		get
		{
			return this.dpdidField;
		}
		set
		{
			this.dpdidField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ema-product-code", IsNullable = true)]
	public string emaproductcode
	{
		get
		{
			return this.emaproductcodeField;
		}
		set
		{
			this.emaproductcodeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ema-ma-number", IsNullable = true)]
	public string emamanumber
	{
		get
		{
			return this.emamanumberField;
		}
		set
		{
			this.emamanumberField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("started-marketing-on")]
	public string startedmarketingon
	{
		get
		{
			return this.startedmarketingonField;
		}
		set
		{
			this.startedmarketingonField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ended-marketing-on")]
	public string endedmarketingon
	{
		get
		{
			return this.endedmarketingonField;
		}
		set
		{
			this.endedmarketingonField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("dosage-form")]
	public string dosageform
	{
		get
		{
			return this.dosageformField;
		}
		set
		{
			this.dosageformField = value;
		}
	}

	/// <remarks/>
	public string strength
	{
		get
		{
			return this.strengthField;
		}
		set
		{
			this.strengthField = value;
		}
	}

	/// <remarks/>
	public string route
	{
		get
		{
			return this.routeField;
		}
		set
		{
			this.routeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("fda-application-number")]
	public string fdaapplicationnumber
	{
		get
		{
			return this.fdaapplicationnumberField;
		}
		set
		{
			this.fdaapplicationnumberField = value;
		}
	}

	/// <remarks/>
	public bool generic
	{
		get
		{
			return this.genericField;
		}
		set
		{
			this.genericField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("over-the-counter")]
	public bool overthecounter
	{
		get
		{
			return this.overthecounterField;
		}
		set
		{
			this.overthecounterField = value;
		}
	}

	/// <remarks/>
	public bool approved
	{
		get
		{
			return this.approvedField;
		}
		set
		{
			this.approvedField = value;
		}
	}

	/// <remarks/>
	public productcountrytype country
	{
		get
		{
			return this.countryField;
		}
		set
		{
			this.countryField = value;
		}
	}

	/// <remarks/>
	public productsourcetype source
	{
		get
		{
			return this.sourceField;
		}
		set
		{
			this.sourceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "product-country-type", Namespace = "http://www.drugbank.ca")]
public enum productcountrytype
{

	/// <remarks/>
	US,

	/// <remarks/>
	Canada,

	/// <remarks/>
	EU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "product-source-type", Namespace = "http://www.drugbank.ca")]
public enum productsourcetype
{

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("FDA NDC")]
	FDANDC,

	/// <remarks/>
	DPD,

	/// <remarks/>
	EMA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "synonym-type", Namespace = "http://www.drugbank.ca")]
public partial class synonymtype
{

	private string languageField;

	private string coderField;

	private string valueField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string language
	{
		get
		{
			return this.languageField;
		}
		set
		{
			this.languageField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string coder
	{
		get
		{
			return this.coderField;
		}
		set
		{
			this.coderField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "salt-type", Namespace = "http://www.drugbank.ca")]
public partial class salttype
{

	private drugbankdrugsaltidtype[] drugbankidField;

	private string nameField;

	private string uniiField;

	private string casnumberField;

	private string inchikeyField;

	private float averagemassField;

	private bool averagemassFieldSpecified;

	private float monoisotopicmassField;

	private bool monoisotopicmassFieldSpecified;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("drugbank-id")]
	public drugbankdrugsaltidtype[] drugbankid
	{
		get
		{
			return this.drugbankidField;
		}
		set
		{
			this.drugbankidField = value;
		}
	}

	/// <remarks/>
	public string name
	{
		get
		{
			return this.nameField;
		}
		set
		{
			this.nameField = value;
		}
	}

	/// <remarks/>
	public string unii
	{
		get
		{
			return this.uniiField;
		}
		set
		{
			this.uniiField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("cas-number")]
	public string casnumber
	{
		get
		{
			return this.casnumberField;
		}
		set
		{
			this.casnumberField = value;
		}
	}

	/// <remarks/>
	public string inchikey
	{
		get
		{
			return this.inchikeyField;
		}
		set
		{
			this.inchikeyField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("average-mass")]
	public float averagemass
	{
		get
		{
			return this.averagemassField;
		}
		set
		{
			this.averagemassField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool averagemassSpecified
	{
		get
		{
			return this.averagemassFieldSpecified;
		}
		set
		{
			this.averagemassFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("monoisotopic-mass")]
	public float monoisotopicmass
	{
		get
		{
			return this.monoisotopicmassField;
		}
		set
		{
			this.monoisotopicmassField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool monoisotopicmassSpecified
	{
		get
		{
			return this.monoisotopicmassFieldSpecified;
		}
		set
		{
			this.monoisotopicmassFieldSpecified = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "classification-type", Namespace = "http://www.drugbank.ca")]
public partial class classificationtype
{

	private string descriptionField;

	private string directparentField;

	private string kingdomField;

	private string superclassField;

	private string classField;

	private string subclassField;

	private string[] alternativeparentField;

	private string[] substituentField;

	/// <remarks/>
	public string description
	{
		get
		{
			return this.descriptionField;
		}
		set
		{
			this.descriptionField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("direct-parent")]
	public string directparent
	{
		get
		{
			return this.directparentField;
		}
		set
		{
			this.directparentField = value;
		}
	}

	/// <remarks/>
	public string kingdom
	{
		get
		{
			return this.kingdomField;
		}
		set
		{
			this.kingdomField = value;
		}
	}

	/// <remarks/>
	public string superclass
	{
		get
		{
			return this.superclassField;
		}
		set
		{
			this.superclassField = value;
		}
	}

	/// <remarks/>
	public string @class
	{
		get
		{
			return this.classField;
		}
		set
		{
			this.classField = value;
		}
	}

	/// <remarks/>
	public string subclass
	{
		get
		{
			return this.subclassField;
		}
		set
		{
			this.subclassField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("alternative-parent")]
	public string[] alternativeparent
	{
		get
		{
			return this.alternativeparentField;
		}
		set
		{
			this.alternativeparentField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("substituent")]
	public string[] substituent
	{
		get
		{
			return this.substituentField;
		}
		set
		{
			this.substituentField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "group-list-type", Namespace = "http://www.drugbank.ca")]
public partial class grouplisttype
{

	private grouptype[] groupField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("group")]
	public grouptype[] group
	{
		get
		{
			return this.groupField;
		}
		set
		{
			this.groupField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "group-type", Namespace = "http://www.drugbank.ca")]
public enum grouptype
{

	/// <remarks/>
	approved,

	/// <remarks/>
	illicit,

	/// <remarks/>
	experimental,

	/// <remarks/>
	withdrawn,

	/// <remarks/>
	nutraceutical,

	/// <remarks/>
	investigational,

	/// <remarks/>
	vet_approved,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "state-type", Namespace = "http://www.drugbank.ca")]
public enum statetype
{

	/// <remarks/>
	solid,

	/// <remarks/>
	liquid,

	/// <remarks/>
	gas,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.drugbank.ca")]
public partial class sequencelisttypeSequence
{

	private string formatField;

	private string valueField;

	public sequencelisttypeSequence()
	{
		this.formatField = "FASTA";
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string format
	{
		get
		{
			return this.formatField;
		}
		set
		{
			this.formatField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value
	{
		get
		{
			return this.valueField;
		}
		set
		{
			this.valueField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.drugbank.ca")]
public enum drugtypeType
{

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("small molecule")]
	smallmolecule,

	/// <remarks/>
	biotech,
}
